[package]
name = "async-listener-demo"
version = "0.0.0"
edition = "2024"

[dependencies]
tokio-fs = "0.1"
tokio = {  version = "1.47" , features = ["io-util", "rt-multi-thread", "macros", "net"] }
tokio-fs-ext = "0.6"