[package]
name = "async-demo"
version = "0.0.0"
edition = "2024"

[dependencies]
tokio-fs = "0.1"
tokio = { version = "1.47.1", features = ["full"] }
tokio-fs-ext = "0.6"
reqwest = { version = "0.12", features = ["json"] }